### ISSUE TITLE
Type definition file is missing explicit dependency on @types/node

### ISSUE THREAD

**Issue by Elephant-Vessel** [gulpjs/async-done#49]
This ... 
```
import { ChildProcess } from "child_process";
import { EventEmitter } from "events";
import { Stream } from "stream";
```
... errors in the log when I'm building my typescript project as these modules are not defined, as I've had no need for the types of node. When I manually added @types/node to my project, I could build without the index.d.ts of async-done writing errors in the log.

**Comment by demurgos** [comment]
The project is avoiding defining global environment variables. It's up to the user to provide them (similarly to the JS lib or DOM definitions). Types from `@types` are a special case since they're from the DT mono-repo enforces a single `@types/node` version.

Add `@types/node` to your dev-dependencies if you wish to use this lib in Node.
